<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RepositoryUrl>https://github.com/Rokoth/Planning</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Rokoth/Planning</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <Version>0.0.15</Version>
    <Description>Сервисные классы приложения</Description>
    <Copyright>2021 Dmitriy Rokoth</Copyright>
    <AssemblyName>Planning.Service</AssemblyName>
    <PackageId>Planning.Service</PackageId>
    <Title>Planning.Service</Title>
    <Authors>Rokoth</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.1" />
    <PackageReference Include="NCalc2" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\DB\DB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
